title: dancesWithMachines
markdown: kramdown

# Left this to respect original author.
author:
  name: Mateusz Kusiak (Timax)
  email: mkusiak.dwm@gmail.com
# The creator of the theme is Sharad Raj Singh Maurya (dev_sharad@outlook.com)
# I had to change this so it displays properly on RSS readers (Thanks Ramiro!).

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
